title: "G1 - Apprentissage statistique"
author: "BÉRU Théodore, CHEBAK Soraya, CLAVIER Mathieu, GUICHARD Victor"
email: "mathieu.clavier@outlook.com"
release: "1"
logo: 'logo.png'

# Short description about the book
description: >-
  Projet M2 Actuariat. Prédiction de cross-selling en assurance. Groupe 1.

execute:
#  execute_notebooks           : auto
  execute_notebooks           : off
  timeout: -1

# HTML-specific settings
html:
  favicon              : "logo.png"
  home_page_in_navbar  : false
  use_edit_page_button : false
  use_repository_button: false
  use_issues_button    : false

# Interact link settings
notebook_interface            : "notebook"

repository:
  url           : "https://github.com/claviermathieu/ISFA-prj-datascience/"
  branch        : main
  path_to_book  : book

sphinx:
    config:
      html_theme_options:
        use_download_button: false
        repository_url: https://www.mclavier.com
        use_issues_button: false
        use_repository_button: false
        use_edit_page_button: false



# Launch button settings
#launch_buttons:
#  binder             : false
#  binderhub          : false
#  binderhub_url      : off
#  jupyterhub         : false
#  thebe              : false
#  colab              : false

# Launch button settings
launch_buttons:
#  notebook_interface: classic #jupyterlab
  binderhub_url: https://mybinder.org
#  colab_url: https://colab.research.google.com


# LaTeX settings



# bibtex_bibfiles:
#    - _bibliography/references.bib
   
# latex:
#   latex_engine                : "pdflatex"
#   use_jupyterbook_latex       : true # use jupyterbook-latex for pdf builds as default
#   latex_documents:
#     targetname: book.tex
    
# sphinx:
#   config:
#     html_show_copyright: false
#     latex_toplevel_sectioning: 'section'
# #    latex_show_urls: 'footnote'
#     latex_elements.papersize: a4paper
#     latex_elements.pointsize: 12pt
    

# google_analytics:
#   mytrackingcode: UA-205698170-1
